import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { Variable } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider >
    <html lang="en">
      <body className={`${inter.className} bg-dark-2`}>{children}</body>
    </html>
    </ClerkProvider>
  );
}
// appearance={{
//   layout:{
//     logoImageUrl:'/icons/logo.svg',
//     socialButtonsVariant:'iconButton',
//   }
//   ,variables:{
//     colorText: '#fff',
//     colorPrimary:'#0E78F9',
//     colorBackground:'#1c1f2e',
//     colorInputBackground:'#252a41',
//     colorInputText:'#fff',
//   }
// }}